packages:
  - 'shared-types'
  - 'platform-core'
  - 'web-app'
  - 'mobile-app'
  - 'mobile'
  - 'desktop-app'
  - 'ui-kit'
  - 'infra'
  - 'site-vitrine'
  - 'imu-miniapps/packages/*'
  - 'imu-games'
  - 'imu-voom'
  - 'imu-resources'
  - 'imu-worlds'
  - 'imu-contests'
  - 'imu-dating'
  - 'imu-smart-home'
  - 'imu-mobility'
  - 'imu-style-beauty'
  - 'imu-sports'
  - 'imu-formations'
  - 'imu-finance'
  - 'imu-library'
  - 'imu-services'
  - 'imu-events'
  - 'imu-music'
  - 'imu-watch'
